name: deploy

# 代码提交到main分支时触发github action
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
              fetch-depth: 0
              submodules: false

        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v3
          with:
              hugo-version: "latest"
              extended: true

        - name: Build Web
          run: hugo -D --config hugo.prod.toml

        - name: Deploy Web
          uses: peaceiris/actions-gh-pages@v4
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              external_repository: 2004ccf/2004CCF
              publish_branch: main
              publish_dir: ./public
              commit_message: auto deploy
